spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 20
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:

  h2:
    console:
      enabled: true

  data:
    rest:
      base-path: /api
      defaultPageSize: 20
      return-body-on-create: true

logging:
  level:
    root: WARN
    com.crevan.restvoting: DEBUG

server.servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
